
[package]
name = "axum-jwt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.4.4", features = ["headers"]}
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version="0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
headers = "0.3"
#jsonwebtoken = "7"
#once_cell = "1.8"
tera = "1.15.0"
tower = "0.4.11"
#lazy_static = "1.4.0"
tower-cookies = "0.4.1"
tower-http = { version = "0.2", features = ["fs"] }
anyhow = "1.0.53"
dotenv = "0.15.0"
#axum-debug = "0.3.2"
sqlx = { version = "0.5.10", features = ["runtime-tokio-native-tls" , "postgres"] }
axum-debug = "0.3.2"
thiserror = "1.0.30"
#askama = { version = "0.11.0", default-features = false, features = ["with-axum", "mime", "mime_guess"] }
#askama_axum = "0.1.0"

[dependencies.sea-orm]
version = "0.5.0"
features = ["macros", "runtime-tokio-native-tls", "debug-print"]
default-features = false

[features]
default = ["sqlx-postgres"]
#sqlx-mysql = ["sea-orm/sqlx-mysql"]
sqlx-postgres = ["sea-orm/sqlx-postgres"]
